export const actionTypes = {
  REGISTER_STUDENT: "REGISTER_STUDENT",
  AUTH_REQUEST_LOADING: "AUTH_REQUEST_LOADING",
  LOGIN_STUDENT_SUCCESS: "LOGIN_STUDENT_SUCCESS",
  LOGIN_STUDENT_FAILURE: "LOGIN_STUDENT_FAILURE",
  CREATE_TOPIC_REQUEST_LOADING: "CREATE_TOPIC_REQUEST_LOADING",
  CREATE_TOPIC_SUCCESS: "CREATE_TOPIC_SUCCESS",
  CREATE_TOPIC_FAILURE: "CREATE_TOPIC_FAILURE",
}
